import type { MetadataRoute } from "next";

/*
 * PWA manifest. Next.js serves this at /manifest.webmanifest and links
 * it from <head> automatically.
 *
 * `display: "standalone"` strips browser chrome on iOS once the user
 * has tapped Share → Add to Home Screen. `theme_color` matches our
 * black surfaces; `background_color` is the splash-screen color shown
 * before the app's first paint.
 *
 * Icons live under public/icons/ and are regenerated by
 * `node scripts/generate-icons.mjs` whenever the design changes.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Automotive",
    short_name: "Automotive",
    description: "Maintenance and metrics for my cars.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#000000",
    theme_color: "#000000",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
